ENV['RAILS_ENV'] ||= ENV['DATABASE_ENV'] || 'test'

require 'active_support/core_ext'
require 'simplecov'
require 'coveralls'

SimpleCov.formatter = Coveralls::SimpleCov::Formatter
SimpleCov.start do
  add_filter '/spec'
  base_path = "#{File.dirname(__FILE__)}/../"
  Dir["#{base_path}lib/casino_core/*.rb"].each do |f|
    f.gsub!(/\A#{base_path}(.+)\.rb\z/, '\1')
    name = File.basename(f).humanize.pluralize
    add_group name, f
  end
end

require 'coveralls'
Coveralls.wear!

require 'database_cleaner'
require 'logger'
require 'webmock/rspec'
require 'casino_core'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

# Requires supporting ruby files with custom matchers and macros, etc,
# in spec/support/ and its subdirectories.
Dir["#{File.dirname(__FILE__)}/support/**/*.rb"].each {|f| require f}

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'


  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
  end

  config.before(:each) do
    CASinoCore.setup ENV['RAILS_ENV']
    CASinoCore::Settings.logger.level = ::Logger::Severity::UNKNOWN
    DatabaseCleaner.clean_with(:truncation)
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end
end
